# Generated by Django 4.2.9 on 2024-04-10 16:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoadSign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=400,
                        validators=[
                            django.core.validators.MinLengthValidator(5),
                            django.core.validators.MaxLengthValidator(400),
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Default sub_text",
                        validators=[
                            django.core.validators.MinLengthValidator(10),
                            django.core.validators.MaxLengthValidator(800),
                        ],
                    ),
                ),
                (
                    "image_link",
                    models.CharField(
                        max_length=400,
                        validators=[
                            django.core.validators.MinLengthValidator(10),
                            django.core.validators.MaxLengthValidator(500),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TraficRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=400,
                        validators=[
                            django.core.validators.MinLengthValidator(5),
                            django.core.validators.MaxLengthValidator(400),
                        ],
                    ),
                ),
                (
                    "sub_title",
                    models.CharField(
                        max_length=400,
                        validators=[
                            django.core.validators.MinLengthValidator(5),
                            django.core.validators.MaxLengthValidator(400),
                        ],
                    ),
                ),
                (
                    "sub_text",
                    models.TextField(
                        default="Default sub_text",
                        validators=[
                            django.core.validators.MinLengthValidator(5),
                            django.core.validators.MaxLengthValidator(1000),
                        ],
                    ),
                ),
                (
                    "image_link",
                    models.CharField(
                        max_length=400,
                        validators=[
                            django.core.validators.MinLengthValidator(5),
                            django.core.validators.MaxLengthValidator(500),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TraficRuleQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=500)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                ("is_saved", models.BooleanField(default=False)),
                ("link", models.CharField(default="", max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="TraficRuleChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(max_length=200)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.traficrulequestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TraficRuleAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_answered", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.traficrulequestion",
                    ),
                ),
                (
                    "selected_choices",
                    models.ManyToManyField(to="myapp.traficrulechoice"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
