# Generated by Django 4.2.9 on 2024-03-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_traficrule_traficruletext"),
    ]

    operations = [
        migrations.AddField(
            model_name="traficruletext",
            name="title",
            field=models.CharField(default="Title", max_length=500),
        ),
    ]
