# Generated by Django 4.2.9 on 2024-03-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_traficrule_traficruletext"),
    ]

    operations = [
        migrations.AddField(
            model_name="traficruletext",
            name="sub_text",
            field=models.CharField(default="Default sub_text", max_length=1000),
        ),
        migrations.AlterField(
            model_name="traficruletext",
            name="image_link",
            field=models.CharField(max_length=1000),
        ),
    ]
