# Generated by Django 4.2.9 on 2024-04-10 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_traficrulechoice_choice_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadsign",
            name="description",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(10),
                    django.core.validators.MaxLengthValidator(800),
                ]
            ),
        ),
    ]
