# Generated by Django 4.2.9 on 2024-04-10 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_roadsign_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadsign",
            name="description",
            field=models.TextField(
                max_length=800,
                validators=[
                    django.core.validators.MinLengthValidator(10),
                    django.core.validators.MaxLengthValidator(800),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="roadsign",
            name="image_link",
            field=models.CharField(
                max_length=500,
                validators=[
                    django.core.validators.MinLengthValidator(10),
                    django.core.validators.MaxLengthValidator(500),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="traficrule",
            name="image_link",
            field=models.CharField(
                max_length=500,
                validators=[
                    django.core.validators.MinLengthValidator(5),
                    django.core.validators.MaxLengthValidator(500),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="traficrule",
            name="sub_text",
            field=models.TextField(
                default="Default sub_text",
                max_length=1000,
                validators=[
                    django.core.validators.MinLengthValidator(5),
                    django.core.validators.MaxLengthValidator(1000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="traficrulechoice",
            name="choice_text",
            field=models.CharField(
                max_length=400,
                validators=[
                    django.core.validators.MinLengthValidator(5),
                    django.core.validators.MaxLengthValidator(400),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="traficrulequestion",
            name="link",
            field=models.CharField(
                max_length=500,
                validators=[
                    django.core.validators.MinLengthValidator(5),
                    django.core.validators.MaxLengthValidator(500),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="traficrulequestion",
            name="question_text",
            field=models.CharField(
                max_length=500,
                validators=[
                    django.core.validators.MinLengthValidator(5),
                    django.core.validators.MaxLengthValidator(500),
                ],
            ),
        ),
    ]
