# Generated by Django 4.2.9 on 2024-03-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_traficruletext_sub_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="link",
            field=models.CharField(default="", max_length=500),
        ),
    ]
