# Generated by Django 4.2.9 on 2024-03-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_traficruletext_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="traficruletext",
            name="sub_text",
            field=models.CharField(default="sub_text", max_length=500),
        ),
    ]
