# Generated by Django 4.2.9 on 2024-04-18 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_alter_roadsign_description_alter_roadsign_image_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traficrule",
            name="sub_text",
            field=models.TextField(
                max_length=1000,
                validators=[
                    django.core.validators.MinLengthValidator(5),
                    django.core.validators.MaxLengthValidator(1000),
                ],
            ),
        ),
    ]
