# Generated by Django 4.2.9 on 2024-03-27 17:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_traficruletext_video_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="traficruletext",
            name="video_link",
        ),
    ]
