# Generated by Django 5.0.4 on 2024-05-09 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_traficrule_sub_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traficrule',
            name='sub_text',
            field=models.TextField(max_length=500, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
