# Generated by Django 4.2.9 on 2024-03-31 18:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_remove_question_is_answered_answer_is_answered"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="difficulty",
        ),
    ]
