# Generated by Django 4.2.9 on 2024-04-01 19:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0010_traficsingalquestion_traficsingalchoice_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TraficSingalAnswer",
            new_name="RoadSignAnswer",
        ),
        migrations.RenameModel(
            old_name="TraficSingalChoice",
            new_name="RoadSignChoice",
        ),
        migrations.RenameModel(
            old_name="TraficSingalQuestion",
            new_name="RoadSignQuestion",
        ),
    ]
