# Generated by Django 4.2.9 on 2024-04-01 23:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0011_rename_traficsingalanswer_roadsignanswer_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Answer",
            new_name="TraficRuleAnswer",
        ),
        migrations.RenameModel(
            old_name="Choice",
            new_name="TraficRuleChoice",
        ),
        migrations.RenameModel(
            old_name="Question",
            new_name="TraficRuleQuestion",
        ),
        migrations.AlterField(
            model_name="roadsignanswer",
            name="selected_choices",
            field=models.ManyToManyField(to="myapp.roadsignchoice"),
        ),
    ]
