# Generated by Django 4.2.9 on 2024-04-02 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0012_rename_answer_traficruleanswer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoadSign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name="RoadSignText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=5000)),
                (
                    "sub_text",
                    models.CharField(default="Default sub_text", max_length=1000),
                ),
                ("image_link", models.CharField(max_length=1000)),
                (
                    "sub_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.roadsign"
                    ),
                ),
            ],
        ),
    ]
